"""empty message

Revision ID: 32290d2894a1
Revises: 1c0e3ca5169a
Create Date: 2023-04-21 14:21:48.874522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32290d2894a1'
down_revision = '1c0e3ca5169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_url',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
