"""empty message

Revision ID: a4a3472a2b19
Revises: 7ca7e94ff80d
Create Date: 2023-04-14 17:44:52.963954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a3472a2b19'
down_revision = '7ca7e94ff80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.Column('user_username', sa.String(length=255), nullable=False),
    sa.Column('review_text', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
